# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Papermap < Formula
  desc "Terminal-native client for Papermap insights"
  homepage "https://github.com/Papermap-ai/papermap-tui"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Papermap-ai/papermap-tui/releases/download/v0.7.1/papermap_0.7.1_darwin_x86_64.tar.gz"
      sha256 "a27545fcd9424ec060353241ab730d85e4d7a0b86277df67035d83f751be2f88"

      define_method(:install) do
        bin.install "papermap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Papermap-ai/papermap-tui/releases/download/v0.7.1/papermap_0.7.1_darwin_arm64.tar.gz"
      sha256 "53f1c2403d7b2ea5f5fa700f19ff1eb0895d907c05cfc94e9efc0ecbc6731067"

      define_method(:install) do
        bin.install "papermap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Papermap-ai/papermap-tui/releases/download/v0.7.1/papermap_0.7.1_linux_x86_64.tar.gz"
      sha256 "d356a64b8390b0e176f89d283fb9b32c18cec9db4aff70ebf3319912090f4952"
      define_method(:install) do
        bin.install "papermap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Papermap-ai/papermap-tui/releases/download/v0.7.1/papermap_0.7.1_linux_arm64.tar.gz"
      sha256 "221b9557f52c4806a3d21a02108704ed2999e1af4c34769bfe9e29be66585160"
      define_method(:install) do
        bin.install "papermap"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/papermap --version")
  end
end
