# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Papermap < Formula
  desc "Terminal-native client for Papermap insights"
  homepage "https://github.com/Papermap-ai/papermap-tui"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Papermap-ai/papermap-tui/releases/download/v0.8.0/papermap_0.8.0_darwin_x86_64.tar.gz"
      sha256 "e0224dfd8926de42d2219803d1ae992bcbef72251c0eba7b5397ca78d2d14d31"

      define_method(:install) do
        bin.install "papermap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Papermap-ai/papermap-tui/releases/download/v0.8.0/papermap_0.8.0_darwin_arm64.tar.gz"
      sha256 "abd16db427f69673f9632a99441dab595be36d6502ba9d5186713ab4e909f7ba"

      define_method(:install) do
        bin.install "papermap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Papermap-ai/papermap-tui/releases/download/v0.8.0/papermap_0.8.0_linux_x86_64.tar.gz"
      sha256 "fd2c79df73e2de16130295edf6aff56e61eb2c5ecf0cc588db1c53bba39f3472"
      define_method(:install) do
        bin.install "papermap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Papermap-ai/papermap-tui/releases/download/v0.8.0/papermap_0.8.0_linux_arm64.tar.gz"
      sha256 "eb9b07f130c9cdc38afd4935577d5980ad6ea305e72f02da22ee91782c960072"
      define_method(:install) do
        bin.install "papermap"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/papermap --version")
  end
end
