# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Papermap < Formula
  desc "Terminal-native client for Papermap insights"
  homepage "https://github.com/Papermap-ai/papermap-tui"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Papermap-ai/papermap-tui/releases/download/v0.7.0/papermap_0.7.0_darwin_x86_64.tar.gz"
      sha256 "c8ec47b547d237dacfaedc6992dd3c569a24c99e85b966b5485f255145d567d0"

      define_method(:install) do
        bin.install "papermap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Papermap-ai/papermap-tui/releases/download/v0.7.0/papermap_0.7.0_darwin_arm64.tar.gz"
      sha256 "fcb2ea6a587f0bfc5cea2a71898c0a72e8d2037c620c1fd4f312e27e4a363e24"

      define_method(:install) do
        bin.install "papermap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Papermap-ai/papermap-tui/releases/download/v0.7.0/papermap_0.7.0_linux_x86_64.tar.gz"
      sha256 "146505944c861ff3f7bc55939f69b2af1755260f3c497ba46c7bc5209e74283b"
      define_method(:install) do
        bin.install "papermap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Papermap-ai/papermap-tui/releases/download/v0.7.0/papermap_0.7.0_linux_arm64.tar.gz"
      sha256 "a063c955ae88565946a339ec4d7f65cf691a972064f3d6a08363bdd7a99d2ab9"
      define_method(:install) do
        bin.install "papermap"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/papermap --version")
  end
end
